# Generated by Django 5.0.2 on 2024-02-19 10:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_pay_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата платежа'),
        ),
    ]
