# Generated by Django 5.0.2 on 2024-02-25 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
