services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    command: "python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    ports:
      - "8000:8000"

  db:
    container_name: postgres
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: project7
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"

  celery:
    container_name: celery
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: "celery -A config worker -l INFO"

volumes:
  db_data:


