# Generated by Django 5.0.2 on 2024-03-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_coursepayment_remove_course_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursepayment',
            name='price_amount',
        ),
        migrations.AddField(
            model_name='coursepayment',
            name='payment_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена платежа'),
        ),
    ]
