# Generated by Django 3.2.25 on 2024-03-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_remove_coursepayment_price_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepayment',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название продукта'),
        ),
    ]
