# Generated by Django 3.2.25 on 2024-03-12 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_coursepayment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepayment',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='Название продукта'),
        ),
    ]
