# Generated by Django 3.2.25 on 2024-03-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_alter_coursepayment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepayment',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название продукта'),
        ),
    ]
